### ISSUE TITLE
Noob question how to connect client on host to cluster on vagrant

### ISSUE THREAD

**Issue by programming-kid** [bcantoni/vagrant-cassandra#2]
I intend to write a nodejs client application which will run on host ( ubuntu ) how do i connect it to cassandra cluster running on vagrant which i p address should i use to connect to cassandra cluster from nodejs client .

Do i have to forward any port from vagrant to host to connect from cassandra nodejs client

**Comment by roman-io** [comment]
If your Vagrant guest uses NAT, you need to configure forward for client in Vagrantfile
```config.vm.network "forwarded_port", guest: 9042, host: 9042```
And then reload vagrant
```vagrant reload```

For additional info about Cassnadra ports:
http://www.datastax.com/documentation/cassandra/2.0/cassandra/security/secureFireWall_r.html

**Comment by bcantoni** [comment]
Thanks @roman-io for providing the info.
