### ISSUE TITLE
[Problem] I'm getting NoHostAvailableException when trying to connect to a Cassandra Cluster

### ISSUE THREAD

**Issue by brenoinojosa** [bcantoni/vagrant-cassandra#3]
So I have followed your tutorials and set up "1.Base" to configure a CassandraDB on a single machine. So far so good. I'm able to use CQLSH, see the Cassandra Service and everything else.

But when I try to run my application, which uses the DataStax driver, I can't connect to my CassandraDB.

I've tried connecting to : localhost, 127.0.0.1, my_vagrant_private_ip, all using 9042 as default port.
Also, I tried telnet on 9160, 9042, didn't work either.

I also did:
- ufw allow the ports I needed
- ufw disable (to allow all ports)
- forwarded the ports on Vagrantfile
- I can see that the firewall allows those ports
- Changed rpc_address and listen_address to 0.0.0.0

I don't know what is wrong. Can you please help?

**Comment by bcantoni** [comment]
@brenoinojosa could you provide a little more info:
* which version of Cassandra have you installed?
* did you use the Tarball or Ubuntu package?
* are you trying to run your application from inside the Vagrant VM (guest), or on your host computer?

From there I can hopefully give some more clues for troubleshooting this.

**Comment by brenoinojosa** [comment]
thanks for the reply, @bcantoni . 

- I'm using Cassandra 2.1.4
- Tarball (http://mirror.nbtelecom.com.br/apache/cassandra/2.1.4/apache-cassandra-2.1.4-bin.tar.gz)
- I'm running my application from my host computer (which is running the vagrant VM).
- Telnetting from inside Vagrant works, outside doesn't.

**Comment by brenoinojosa** [comment]
Oh, btw. I got it fixed in Cassandra 2.1.5. There's a new flag that resolves the problem. :)

**Comment by bcantoni** [comment]
@brenoinojosa what was the issue/flag you found in Cassandra 2.1.5? I may want to add that to the docs here in case others run into it.
