### ISSUE TITLE
Cassandra check for java version fails

### ISSUE THREAD

**Issue by manuel-zulian** [bcantoni/vagrant-cassandra#4]
Not really a bug of this project, but more of dse itself. As pointed out [here](http://stackoverflow.com/questions/36867832/cassandra-2-0-and-later-require-java-7u25-or-later-but-im-using-jdk1-7-0-101) the dse installer checks for the presence of java in the wrong way, which is currently failing for the jdk7u101. The fix on the same page above works (commenting out the check in the script).

Reporting this here because I wasted a lot of time trying to solve this, so I hope it can help someone else too (not really sure if this should be addressed in this project, but at least this can help pointing in the right direction).

**Comment by mshanak** [comment]
nodetool status
Cassandra 2.0 and later require Java 7u25 or later.

**Comment by manuel-zulian** [comment]
Pretty sure this was fixed by 14fd7cf266e4f8790acdfd80b819337a57c5f612 .
