### ISSUE TITLE
Update Java 8

### ISSUE THREAD

**Issue by godzillalad** [bcantoni/vagrant-cassandra#7]
fantastic resource getting Cassandra up and running almost seamlessly

With some recent updates there are a couple of gotchas with java version so I had to upgrade to OpenJDK 8 in the Vagrantfile

```
# configure openJDK repo
add-apt-repository ppa:openjdk-r/ppa
apt-get update
# install Java first, then DataStax Community Edition
apt-get install openjdk-8-jdk
```

**Comment by bcantoni** [comment]
Thanks for the feedback here; in subsequent updates (including one today) I've adjusted the templates to grab the latest OpenJDK 8 now.
